### ISSUE TITLE
The information in the notification might be too much

### ISSUE THREAD

**Issue by Feichtmeier** [fthx/snap-manager#1]
Hi @fthx :wave: 
Once again I am using one more of your nice gnome shell extensions. This one is especially useful since gnome software + the snap plugin is not really working well sadly.

Anyways, I think the information in the notification might be too much 
![Bildschirmfoto von 2021-03-09 11-31-17](https://user-images.githubusercontent.com/15329494/110457750-41778380-80cb-11eb-9951-de2af813a610.png)

I think just the list of applications should be enough, i.e.
vlc
firefox
flameshot

Wdyt?

**Comment by fthx** [comment]
Hi,

For sure it would be enough. I did not look at a solution to extract only app names from `snap refresh --list`.
I can do that, but not before Thursday because linear algebra stuff can't wait. ;-)

And I have some BaBar issues with GNOME 40. Of course...

**Comment by fthx** [comment]
https://github.com/fthx/snap-manager/commit/23f507e42fe3ee0562d71688d0ce978219c4af91
Tell me if it's ok, so I could push it to GS extensions website.

**Comment by fthx** [comment]
It's already reviewed, available through extensions updates. :-)

**Comment by Feichtmeier** [comment]
Cool thank you! Didn't have the time to test yesterday, sorry :(

**Comment by fthx** [comment]
I did some code cleanup too, I like to write some neat code. At least, as far as I'm able to do!!   ^_^

Well, this extension is quite hackish though... :-) I would like to async search for refresh list without writing this to a file, but that's the only way I found, using bash. If you know some magic gjs commands here?

The only drawback I see to the new setup is that the notification when no updates are available had to be set to CRITICAL, as NORMAL ones do only display 1 line of message... :-(
I'll have a look at this again.

Edit: I did.
NORMAL does unfold on hover BUT if you miss it, it appears in message tray and you cannot read the refresh notification... So I keep CRITICAL.

**Comment by Feichtmeier** [comment]
I am not really good in GJS, sorry :)
Your change is already on my system, thanks again!

![grafik](https://user-images.githubusercontent.com/15329494/110630318-81ab3480-81a5-11eb-9a54-e4f8104a772a.png)

**Comment by fthx** [comment]
Well, I see a problem here: 5 snaps? Hmm...
:-)
I look at this.

**Comment by fthx** [comment]
Ok, notification is limited to 6 lines. So:
- the updates counter is right (I tested with 2 snaps and it was correct)
- the 5th of your snaps to be updated is simply not displayed
- the Auto updates state is under this 5th snap so not displayed too, that's more annoying

So I will display the snap names without linebreaks...

**Comment by fthx** [comment]
Done and tested!
