### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Ricky-Tigg** [fthx/snap-manager#2]
**Tested on:** Gnome 40.0; **Component:** snap-manager@fthx, v. 30.

Is this extension aimed to enable translation files? It would be convenient to have it to match `localectl` when a related translated-content file exits.

**Comment by fthx** [comment]
I'm not planning any translation soon.
Never should to say never, though...

**Comment by ghost** [comment]
It would be great the extension be translated, I can work on it.
