### ISSUE TITLE
No Notification when nothing new

### ISSUE THREAD

**Issue by skarmoutsosv** [fthx/snap-manager#6]
Notification message should not appear just to inform there is nothing to update, or the time of the next check.
I understand that it is useful to know that everything is up to date but it is more important to not distract user.
If all applications will do the same users will permanently stop their workflow and spend all of their time to read notifications.

**Comment by fthx** [comment]
*Hi*,

I'll change this today. Note that the notification happens once a session. That should not break your workflow.

**Comment by skarmoutsosv** [comment]
Well, maybe workflow was not the correct word but it should always be nice to have less to read while starting a session.
Thank you for your nice extension and your lightning fast issue reaction.

**Comment by fthx** [comment]
Intermediate solution : info anyway (esp. about refresh date) but non urgent notif (= no need to click).
https://github.com/fthx/snap-manager/commit/50ccf3b6b1ab5e524ba1c75300db61604ce9520f

**Comment by fthx** [comment]
Uploaded in Gnome ext website, update should happen soon.
