### ISSUE TITLE
Gnome 42

### ISSUE THREAD

**Issue by wbutter** [fthx/snap-manager#7]
Does not appear to have compatibility with gnome-shell version 42.

Note, when I upgraded to Ubuntu 22.04, snap-manager stopped working, and gnome extensions reports that "The extension is incompatible with the current GNOME version".  I find this to be a really nice tool and I hope you can fix this incompatibility.  Thanks!

**Comment by Alfagiovanni56** [comment]
Yeah, I hope that this will soon be fixed. Love this extension, which improves the transparency a lot and offers better user control.

**Comment by fthx** [comment]
Please use snap manager lite extension.
I use it in GS 42.

You lose the startup update check but nothing else.

**Comment by wbutter** [comment]
This works great!  Thanks!
